
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.geijpkyhyeguxhsoynvv
spring.datasource.password=frMQ_-FQyG9J5Ep
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.swagger-ui.path=/swagger-ui.html
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect